# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'PixelPalette' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Util
  pod 'SnapKit'			, '5.0.1'
  pod 'Toast-Swift'		, '5.0.1'

  # Ad
  pod 'Google-Mobile-Ads-SDK'

end
